[project]
name = "video-downloader-cli"
version = "0.1.0"
dependencies = [
    "psycopg2-binary",
    "yt-dlp",
    "Pillow",
]

[project.scripts]
videodownloader-cli = "cli:main"
videodownloader-web = "start_web:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["cli", "database", "db_operations", "video_download", "models", "start_web", "thumbnail_art"]
