[project]
name = "video-downloader-cli"
version = "0.1.0"
dependencies = [
    "psycopg2-binary",
    "yt-dlp",
    "Pillow",
    "textual"
]

[project.scripts]
videodownloader-cli = "backend.cli.cli:main"
videodownloader-web = "backend.start_web:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["backend", "backend.cli", "backend.db", "backend.services"]
package-data = { "backend.cli" = ["cli.tcss"] }
